// Scenes / locations data. Positions are in percent of .scene-bg
// Each task has: id, label, emoji, prompt (voice), prop (type),
// targets (array of {emoji/img, x%, y%, accepts:propType, needs:count}),
// successLine (voice)

export const LOCATIONS = [
  {
    id: 'qingtang',
    name: '青塘園',
    emoji: '🦆',
    color: 'green',
    candyEmoji: '🍏',
    hours: [8, 21],
    bg: 'assets/images/locations/bg_qingtang.png',
    bgFallback: 'linear-gradient(180deg, #cdeafd 0%, #a4e3b7 100%)',
    bgEmoji: '🏞',
    tasks: [
      {
        id: 'qingtang_feed_duck',
        label: '餵鴨鵝',
        emoji: '🐤',
        prompt: '把麵包給鴨鴨和鵝！',
        success: '鴨鴨好開心！',
        prop: { type:'bread', emoji:'🍞', img:'assets/images/props/item_bread.png' },
        targets: [
          { id:'duck',  emoji:'🦆', img:'assets/images/animals/animal_duck.png',  x:25, y:60, accepts:'bread' },
          { id:'goose', emoji:'🦢', img:'assets/images/animals/animal_goose.png', x:65, y:55, accepts:'bread' },
        ],
        needs: 2,
      },
      {
        id: 'qingtang_feed_fish',
        label: '餵魚',
        emoji: '🐟',
        prompt: '撒魚飼料給小魚吃！',
        success: '魚魚游過來了！',
        prop: { type:'fishfood', emoji:'🐟', img:'assets/images/props/item_fishfood.png' },
        targets: [
          { id:'fish', emoji:'🐠', img:'assets/images/animals/animal_fish.png', x:50, y:70, accepts:'fishfood' },
        ],
        needs: 3,
      },
      {
        id: 'qingtang_play_dog',
        label: '跟狗玩',
        emoji: '🐕',
        prompt: '丟飛盤給狗狗！',
        success: '狗狗叼回來了！',
        prop: { type:'frisbee', emoji:'🥏', img:'assets/images/props/item_frisbee.png' },
        targets: [
          { id:'dog', emoji:'🐕', img:'assets/images/animals/animal_dog.png', x:50, y:55, accepts:'frisbee' },
        ],
        needs: 2,
      },
    ],
  },
  {
    id: 'kindergarten',
    name: '田園幼稚園',
    emoji: '🏫',
    color: 'yellow',
    candyEmoji: '🍋',
    hours: [8, 12],
    bg: 'assets/images/locations/bg_kindergarten.png',
    bgFallback: 'linear-gradient(180deg, #fff3c4 0%, #ffe38a 100%)',
    bgEmoji: '🏫',
    tasks: [
      {
        id: 'kg_eat',
        label: '自己吃飯',
        emoji: '🍚',
        prompt: '用湯匙自己吃飯飯！',
        success: '吃光光，好棒！',
        prop: { type:'spoon', emoji:'🥄', img:'assets/images/props/item_spoon_bowl.png' },
        targets: [
          { id:'bowl', emoji:'🍚', x:50, y:55, accepts:'spoon' },
        ],
        needs: 3,
      },
      {
        id: 'kg_brush',
        label: '自己刷牙',
        emoji: '🪥',
        prompt: '刷刷刷，把牙齒刷乾淨！',
        success: '牙齒閃亮亮！',
        prop: { type:'toothbrush', emoji:'🪥', img:'assets/images/props/item_toothbrush.png' },
        targets: [
          { id:'mouth', emoji:'😁', x:50, y:55, accepts:'toothbrush' },
        ],
        needs: 3,
      },
      {
        id: 'kg_bike',
        label: '學腳踏車',
        emoji: '🚴',
        prompt: '戴上安全帽騎腳踏車！',
        success: '騎得好穩喔！',
        prop: { type:'helmet', emoji:'⛑️', img:'assets/images/props/item_helmet.png' },
        targets: [
          { id:'head', emoji:'🚴', x:50, y:55, accepts:'helmet' },
        ],
        needs: 1,
      },
    ],
  },
  {
    id: 'nursery',
    name: '金培恩托兒所',
    emoji: '🧸',
    color: 'orange',
    candyEmoji: '🍊',
    hours: [8, 12],
    bg: 'assets/images/locations/bg_nursery.png',
    bgFallback: 'linear-gradient(180deg, #ffe0c2 0%, #ffb370 100%)',
    bgEmoji: '🧸',
    tasks: [
      {
        id: 'ny_bottle',
        label: '喝奶奶',
        emoji: '🍼',
        prompt: '把奶瓶拿給小寶寶！',
        success: '咕嚕咕嚕好飽！',
        prop: { type:'bottle', emoji:'🍼', img:'assets/images/props/item_bottle.png' },
        targets: [
          { id:'baby', emoji:'👶', x:50, y:55, accepts:'bottle' },
        ],
        needs: 2,
      },
      {
        id: 'ny_wash',
        label: '自己洗手',
        emoji: '🧼',
        prompt: '擦肥皂搓搓手！',
        success: '手手香香！',
        prop: { type:'soap', emoji:'🧼', img:'assets/images/props/item_soap.png' },
        targets: [
          { id:'hand', emoji:'🤲', x:50, y:55, accepts:'soap' },
        ],
        needs: 3,
      },
      {
        id: 'ny_toy',
        label: '收玩具',
        emoji: '🧸',
        prompt: '把玩具放進玩具箱！',
        success: '房間好乾淨！',
        prop: { type:'toy', emoji:'🧸', img:'assets/images/props/item_toy_block.png' },
        targets: [
          { id:'toybox', emoji:'📦', x:70, y:60, accepts:'toy' },
        ],
        needs: 3,
      },
    ],
  },
  {
    id: 'beach',
    name: '海邊',
    emoji: '🏖',
    color: 'blue',
    candyEmoji: '🟦',
    hours: [8, 21],
    bg: 'assets/images/locations/bg_beach.png',
    bgFallback: 'linear-gradient(180deg, #9dd6ff 0%, #ffe8a9 100%)',
    bgEmoji: '🏖',
    tasks: [
      {
        id: 'beach_sand',
        label: '堆城堡',
        emoji: '🏰',
        prompt: '用沙桶堆沙堡！',
        success: '好厲害的城堡！',
        prop: { type:'sandbucket', emoji:'🪣', img:'assets/images/props/item_sandbucket.png' },
        targets: [
          { id:'castle', emoji:'🏖', x:50, y:70, accepts:'sandbucket' },
        ],
        needs: 3,
      },
      {
        id: 'beach_wave',
        label: '踏浪',
        emoji: '🌊',
        prompt: '去踩踩小浪花！',
        success: '波波波，好涼！',
        prop: { type:'foot', emoji:'👣', img:null },
        targets: [
          { id:'wave', emoji:'🌊', x:50, y:50, accepts:'foot' },
        ],
        needs: 5,
      },
      {
        id: 'beach_crab',
        label: '抓螃蟹',
        emoji: '🦀',
        prompt: '用水桶蓋住螃蟹！',
        success: '抓到囉！',
        prop: { type:'waterbucket', emoji:'🪣', img:'assets/images/props/item_waterbucket.png' },
        targets: [
          { id:'crab1', emoji:'🦀', img:'assets/images/animals/animal_crab.png', x:30, y:65, accepts:'waterbucket' },
          { id:'crab2', emoji:'🦀', img:'assets/images/animals/animal_crab.png', x:70, y:70, accepts:'waterbucket' },
          { id:'crab3', emoji:'🦀', img:'assets/images/animals/animal_crab.png', x:50, y:60, accepts:'waterbucket' },
        ],
        needs: 3,
      },
    ],
  },
  {
    id: 'dinomountain',
    name: '恐龍山',
    emoji: '🦖',
    color: 'red',
    candyEmoji: '🍓',
    hours: [8, 21],
    bg: 'assets/images/locations/bg_dinomountain.png',
    bgFallback: 'linear-gradient(180deg, #c8e6ff 0%, #ff9a9a 100%)',
    bgEmoji: '🦖',
    tasks: [
      {
        id: 'dino_feed',
        label: '餵恐龍',
        emoji: '🍖',
        prompt: '把肉肉給恐龍吃！',
        success: '啊嗚！好好吃！',
        prop: { type:'meat', emoji:'🍖', img:'assets/images/props/item_meat.png' },
        targets: [
          { id:'dinobig', emoji:'🦖', img:'assets/images/animals/animal_dino_big.png', x:50, y:55, accepts:'meat' },
        ],
        needs: 2,
      },
      {
        id: 'dino_climb',
        label: '爬山',
        emoji: '⛰',
        prompt: '點階梯爬到山頂！',
        success: '山頂到囉！',
        prop: { type:'step', emoji:'⬆️', img:null },
        targets: [
          { id:'mountain', emoji:'⛰', x:50, y:50, accepts:'step' },
        ],
        needs: 5,
      },
      {
        id: 'dino_cage',
        label: '關恐龍',
        emoji: '🏚',
        prompt: '把小恐龍關回籠子！',
        success: '小恐龍回家了！',
        prop: { type:'cage', emoji:'🏚', img:'assets/images/props/item_cage.png' },
        targets: [
          { id:'dinosmall1', emoji:'🦕', img:'assets/images/animals/animal_dino_small.png', x:25, y:65, accepts:'cage' },
          { id:'dinosmall2', emoji:'🦕', img:'assets/images/animals/animal_dino_small.png', x:55, y:70, accepts:'cage' },
          { id:'dinosmall3', emoji:'🦕', img:'assets/images/animals/animal_dino_small.png', x:75, y:60, accepts:'cage' },
        ],
        needs: 3,
      },
    ],
  },
  {
    id: 'office',
    name: '辦公室',
    emoji: '💼',
    color: 'purple',
    candyEmoji: '🍇',
    hours: [12, 18],
    bg: 'assets/images/locations/bg_office.png',
    bgFallback: 'linear-gradient(180deg, #ecd9ff 0%, #c8a8ff 100%)',
    bgEmoji: '💼',
    tasks: [
      {
        id: 'office_keyboard',
        label: '打電腦',
        emoji: '⌨️',
        prompt: '幫爸爸打鍵盤！',
        success: '打字好快！',
        prop: { type:'keyboard', emoji:'⌨️', img:'assets/images/props/item_keyboard.png' },
        targets: [
          { id:'computer', emoji:'💻', x:50, y:50, accepts:'keyboard' },
        ],
        needs: 3,
      },
      {
        id: 'office_duck',
        label: '遛鴨子',
        emoji: '🦆',
        prompt: '牽著鴨子去散步！',
        success: '鴨鴨跟著你走！',
        prop: { type:'leash', emoji:'🪢', img:'assets/images/props/item_leash.png' },
        targets: [
          { id:'officeduck', emoji:'🦆', img:'assets/images/animals/animal_duck.png', x:50, y:60, accepts:'leash' },
        ],
        needs: 2,
      },
      {
        id: 'office_cuckoo',
        label: '布穀鳥',
        emoji: '🕰',
        prompt: '點時鐘讓布穀鳥跳出來！',
        success: '咕咕！時間到！',
        prop: { type:'clocktap', emoji:'👆', img:null },
        targets: [
          { id:'clock', emoji:'🕰', img:'assets/images/props/item_cuckoo_clock.png', x:50, y:40, accepts:'clocktap' },
        ],
        needs: 3,
      },
    ],
  },
];

export function findLocation(id) {
  return LOCATIONS.find(l => l.id === id);
}
export function findTask(locId, taskId) {
  const loc = findLocation(locId);
  return loc?.tasks.find(t => t.id === taskId);
}
